### ISSUE TITLE
ARM: Login into Web UI does not work

### ISSUE THREAD

**Issue by napopa** [v00d00/gerbera#105]
I've installed gerbera 1.0.0 using the provided scripts to install libtag and libupnp. Everything compiles fine and I can connect to the webUI but when I enter username and password nothing happens (I enabled accounts in my config file). Chrome developer tools show the following error when clicking on login:

```
GET http://192.168.178.149:49152/content/interface?req_type=auth&return_type=xml&sid=null&action=get_token net::ERR_CONTENT_LENGTH_MISMATCH

(anonymous)	@	VM600:1
request	@	prototype.js:1421
initialize	@	prototype.js:1385
(anonymous)	@	prototype.js:329
klass	@	prototype.js:89
authenticate	@	auth.js:36
(anonymous)	@	VM762:1
```

**Comment by v00d00** [comment]
It works for me in both chrome and firefox :(

**Comment by v00d00** [comment]
Maybe try running with `--debug` and see if the server logs anything helpful?

**Comment by napopa** [comment]
Hi v00d00, here's a full dump of the debug log 

https://pastebin.com/km34Nm4T

The relevant bit is at the end, generated connecting to the webUI and trying to login

```
2017-07-02 13:22:48   DEBUG: [src/action_request.cc:100] update(): ActionRequest::update(): converted to iXML, code 0
2017-07-02 13:22:48   DEBUG: [src/server.cc:338] upnp_callback(): returning 0
2017-07-02 13:22:48   DEBUG: [src/server.cc:284] upnp_callback(): start
2017-07-02 13:22:48   DEBUG: [src/server.cc:359] upnp_actions(): start
2017-07-02 13:22:48   DEBUG: [src/upnp_cds_actions.cc:186] process_action_request(): start
2017-07-02 13:22:48   DEBUG: [src/upnp_cds_actions.cc:41] upnp_action_Browse(): start
2017-07-02 13:22:48   DEBUG: [src/storage/sql_storage.cc:702] browse(): QUERY: SELECT "f"."id","f"."ref_id","f"."parent_id","f"."object_type","f"."upnp_class","f"."dc_title","f"."location","f"."location_hash","f"."metadata","f"."auxdata","f"."resources","f"."update_id","f"."mime_type","f"."flags","f"."track_number","f"."service_id","rf"."upnp_class","rf"."location","rf"."metadata","rf"."auxdata","rf"."resources","rf"."mime_type","rf"."service_id","as"."persistent" FROM "mt_cds_object" "f" LEFT JOIN "mt_cds_object" "rf" ON "f"."ref_id"="rf"."id" LEFT JOIN "mt_autoscan" "as" ON "as"."obj_id"="f"."id"  WHERE "f"."parent_id"=1 ORDER BY ("f"."object_type"=1) DESC, "f"."dc_title" LIMIT 100 OFFSET 0
2017-07-02 13:22:48   DEBUG: [src/upnp_cds_actions.cc:142] upnp_action_Browse(): end
2017-07-02 13:22:48   DEBUG: [src/upnp_cds_actions.cc:213] process_action_request(): ContentDirectoryService::process_action_request: end
2017-07-02 13:22:48   DEBUG: [src/action_request.cc:86] update(): ActionRequest::update():
<u:BrowseResponse xmlns:u="urn:schemas-upnp-org:service:ContentDirectory:1"><Result>&lt;DIDL-Lite xmlns=&quot;urn:schemas-upnp-org:metadata-1-0/DIDL-Lite/&quot; xmlns:dc=&quot;http://purl.org/dc/elements/1.1/&quot; xmlns:upnp=&quot;urn:schemas-upnp-org:metadata-1-0/upnp/&quot;/&gt;</Result><NumberReturned>0</NumberReturned><TotalMatches>0</TotalMatches><UpdateID>0</UpdateID></u:BrowseResponse>

2017-07-02 13:22:48   DEBUG: [src/action_request.cc:100] update(): ActionRequest::update(): converted to iXML, code 0
2017-07-02 13:22:48   DEBUG: [src/server.cc:338] upnp_callback(): returning 0
2017-07-02 13:22:52   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_config, Path: (null)
2017-07-02 13:22:52   DEBUG: [src/web_callbacks.cc:143] web_open(): web_open(): /content/interface?req_type=auth&return_type=xml&sid=null&action=get_config
2017-07-02 13:22:52   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_config, Path: (null)
2017-07-02 13:22:52   DEBUG: [src/singleton.cc:69] registerSingleton(): registering new singleton... - 9 -> 10
2017-07-02 13:22:52   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_sid, Path: (null)
2017-07-02 13:22:52   DEBUG: [src/web_callbacks.cc:143] web_open(): web_open(): /content/interface?req_type=auth&return_type=xml&sid=null&action=get_sid
2017-07-02 13:22:52   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_sid, Path: (null)
2017-07-02 13:22:52   DEBUG: [src/web/auth.cc:137] process(): checking/getting sid...
2017-07-02 13:22:52   DEBUG: [src/timer.cc:66] addTimerSubscriber(): Adding subscriber... interval: 300 once: 0
2017-07-02 13:23:12   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token, Path: (null)
2017-07-02 13:23:12   DEBUG: [src/web_callbacks.cc:143] web_open(): web_open(): /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token
2017-07-02 13:23:12   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/interface?req_type=auth&return_type=xml&sid=null&action=get_token, Path: (null)
```

**Comment by v00d00** [comment]
That looks fine. Which version of chrome are you using?

**Comment by napopa** [comment]
59.0.3071.115 (Official Build) (64-bit)

**Comment by v00d00** [comment]
As its ERR_CONTENT_LENGTH_MISMATCH, can you look in dev tools and see what the header for content type says, vs the actual content size?

**Comment by Gesk** [comment]
I have the same problem. I installed the Ubuntu version from the ppa (running Ubuntu 16.04 arm).
I can reach the login page but the login button doesn't work. I am actually wondering if it should show at all since security is disabled in the configuration. Using chrome Version 59.0.3071.115 (Official Build) (64-bit) from another computer.

**Comment by v00d00** [comment]
Do you get a token back from the call? Can you post it and the headers?

**Comment by v00d00** [comment]
Can you try with the latest master please? Specifically https://github.com/v00d00/gerbera/commit/911feb6cfa93a919a1a747a03d0a6b9680ff6002 helped here with non-ascii symbols.

**Comment by mehrdd** [comment]
@v00d00 

In Inspector :

```
GET http://192.168.1.28:49152/content/interface?req_type=auth&return_type=xml&sid=null&action=get_token net::ERR_CONTENT_LENGTH_MISMATCH
```

**Comment by napopa** [comment]
Just compiled the latest master, got the same error:

```
GET http://192.168.178.149:49152/content/interface?req_type=auth&return_type=xml&sid=null&action=get_token net::ERR_CONTENT_LENGTH_MISMATCH

request @ prototype.js:1421
initialize @ prototype.js:1385
(anonymous) @ prototype.js:329
klass @ prototype.js:89
authenticate @ auth.js:36
(anonymous) @ VM208:1
```
![image](https://user-images.githubusercontent.com/1825236/28040957-7e404822-65bf-11e7-88b3-44401aef0fc9.png)

**Comment by v00d00** [comment]
@napopa thanks for testing. Are you running on ARM too?

**Comment by napopa** [comment]
@v00d00 yes, raspberrypi 3 B

**Comment by v00d00** [comment]
I need to try and replicate this on an ARM VM.

(if not I've just ordered a shiny new RPi 3 which should arrive tomorrow)

**Comment by v00d00** [comment]
So RPI3 with Gerbera from the PPA exhibits the same issue as you guys are reporting

**Comment by antenore** [comment]
Same here, last checkout from master.

**Comment by antenore** [comment]
With Firefox 50.1.0 the login works, on the contrary with Firefox version 54.0.0.1 it doesn't.

I've tested on Fedora (the server and one of the clients) and from an arch linux client.

Unlucky I don't have many versions of Firefox to try to get which version exactly is "broken".

I'd say is a regression on firefox, or whatever, and not an issue of gerbera.

**Comment by v00d00** [comment]
The content-size is definitely incorrect. Why is still another question, looks overflowy to me.

**Comment by AlwaysTheHardWay** [comment]
I've installed Gerbera on an Odroid XU4 and have had this same problem. I tried both firefox and chromium and the submit button to log in is throwing unrecognized whence.

**Comment by AlwaysTheHardWay** [comment]
And I tried turning accounts off and also changing the user and password. In chromium it throws the whence error and in firefox it does nothing.

**Comment by v00d00** [comment]
I haven't had a chance to look at this yet. I should hopefully have some time this weekend.

**Comment by AlwaysTheHardWay** [comment]
Okay thank you very much.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ian Whyman <notifications@github.com> Date: 7/28/17  8:25 AM  (GMT-05:00) To: v00d00/gerbera <gerbera@noreply.github.com> Cc: AlwaysTheHardWay <hasitsthorns@aim.com>, Comment <comment@noreply.github.com> Subject: Re: [v00d00/gerbera] Login into Web UI does not work (#105) 
I haven't had a chance to look at this yet. I should hopefully have some time this weekend.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v00d00/gerbera","title":"v00d00/gerbera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/v00d00/gerbera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@v00d00 in #105: I haven't had a chance to look at this yet. I should hopefully have some time this weekend."}],"action":{"name":"View Issue","url":"https://github.com/v00d00/gerbera/issues/105#issuecomment-318638750"}}}

**Comment by LinuxUser2017** [comment]
Hello,

I also can't log into the server - I also don't know what username / password to use.

I'm on an Rpi 3. 

Linux securitypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux

**Comment by v00d00** [comment]
Still having issues with Ubuntu on the Pi3, going to try a gentoo install.

**Comment by AlwaysTheHardWay** [comment]
I don't know what that is lol. I installed it on an odroid using their Ubuntu for the xu4.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ian Whyman <notifications@github.com> Date: 7/30/17  9:05 AM  (GMT-05:00) To: v00d00/gerbera <gerbera@noreply.github.com> Cc: AlwaysTheHardWay <hasitsthorns@aim.com>, Comment <comment@noreply.github.com> Subject: Re: [v00d00/gerbera] ARM: Login into Web UI does not work (#105) 
Still having issues with Ubuntu on the Pi3, going to try a gentoo install.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v00d00/gerbera","title":"v00d00/gerbera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/v00d00/gerbera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@v00d00 in #105: Still having issues with Ubuntu on the Pi3, going to try a gentoo install."}],"action":{"name":"View Issue","url":"https://github.com/v00d00/gerbera/issues/105#issuecomment-318900733"}}}

**Comment by LinuxUser2017** [comment]
I'm on Raspian.

**Comment by AlwaysTheHardWay** [comment]
I have mediatomb running successfully on it. But I shut off the login screen. The problem is it just doesn't seem to recognize and be able to serve a lot of file types. I have been playing with Plex on my windows boxes.  Gerbera I figured was an update that could probably handle more things than mediatomb. But I was stuck on the login not working.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: LinuxUser2017 <notifications@github.com> Date: 7/30/17  6:20 PM  (GMT-05:00) To: v00d00/gerbera <gerbera@noreply.github.com> Cc: AlwaysTheHardWay <hasitsthorns@aim.com>, Comment <comment@noreply.github.com> Subject: Re: [v00d00/gerbera] ARM: Login into Web UI does not work (#105) 
I'm on Raspian.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v00d00/gerbera","title":"v00d00/gerbera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/v00d00/gerbera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@LinuxUser2017 in #105: I'm on Raspian. \r\n"}],"action":{"name":"View Issue","url":"https://github.com/v00d00/gerbera/issues/105#issuecomment-318934014"}}}

**Comment by v00d00** [comment]
So couldn't replicate this on Gentoo ARM64. Will dig out another SD card and try 32 bit

**Comment by AlwaysTheHardWay** [comment]
I am on 64-bit Ubuntu on xu4 odroid from hard kernel. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ian Whyman <notifications@github.com> Date: 7/31/17  5:48 PM  (GMT-05:00) To: v00d00/gerbera <gerbera@noreply.github.com> Cc: AlwaysTheHardWay <hasitsthorns@aim.com>, Comment <comment@noreply.github.com> Subject: Re: [v00d00/gerbera] ARM: Login into Web UI does not work (#105) 
So couldn't replicate this on Gentoo ARM64. Will dig out another SD card and try 32 bit

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v00d00/gerbera","title":"v00d00/gerbera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/v00d00/gerbera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@v00d00 in #105: So couldn't replicate this on Gentoo ARM64. Will dig out another SD card and try 32 bit"}],"action":{"name":"View Issue","url":"https://github.com/v00d00/gerbera/issues/105#issuecomment-319206417"}}}

**Comment by LinuxUser2017** [comment]
Hi,

Is there anything I can do to help? This post is tagged "need info", but I'm not sure what info would be useful.

**Comment by v00d00** [comment]
I think I have all the information I need.

What is needed is that someone steps through the code with a debugger, and works out what is going on on ARM/Ubuntu.

**Comment by bh** [comment]
I can confirm this issue on the latest master (e0c8e2d524) on Archlinux ARM (Raspberry Pi 3). I has been compiled with this PKGBUILD: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=gerbera-git

**Comment by v00d00** [comment]
Status update, I am waiting for replacement microsd card to arrive to my rpi3 so I can debug this.

**Comment by AlwaysTheHardWay** [comment]
Okay thanks.


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ian Whyman <notifications@github.com> Date: 8/6/17  7:30 AM  (GMT-05:00) To: v00d00/gerbera <gerbera@noreply.github.com> Cc: AlwaysTheHardWay <hasitsthorns@aim.com>, Comment <comment@noreply.github.com> Subject: Re: [v00d00/gerbera] ARM: Login into Web UI does not work (#105) 
Status update, I am waiting for replacement microsd card to arrive to my rpi3 so I can debug this.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v00d00/gerbera","title":"v00d00/gerbera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/v00d00/gerbera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@v00d00 in #105: Status update, I am waiting for replacement microsd card to arrive to my rpi3 so I can debug this."}],"action":{"name":"View Issue","url":"https://github.com/v00d00/gerbera/issues/105#issuecomment-320501188"}}}

**Comment by EngelOfChipolata** [comment]
I have the same issue on Raspberry Pi 3 B running on raspbian Jessie. Gerbera has been compiled from the source.

**Comment by v00d00** [comment]
So I've had a quick chance to look at this, as far as I can see right now, Gerbera is doing everything correctly -  but for some reason libupnp is only reading the first byte from the buffer we build.

I guess we are hitting some error condition in their code, so I will have to spend more time debugging that.

(you can see this yourself if you get a `<` as the the body of the AJAX calls in dev tools)

**Comment by AlwaysTheHardWay** [comment]
Ok Ian thanks. I have been messing around with plex to see if I can get that to work. 


Sent from my Verizon, Samsung Galaxy smartphone
-------- Original message --------From: Ian Whyman <notifications@github.com> Date: 8/12/17  6:50 AM  (GMT-05:00) To: v00d00/gerbera <gerbera@noreply.github.com> Cc: AlwaysTheHardWay <hasitsthorns@aim.com>, Comment <comment@noreply.github.com> Subject: Re: [v00d00/gerbera] ARM: Login into Web UI does not work (#105) 
So I've had a quick chance to look at this, as far as I can see right now, Gerbera is doing everything correctly -  but for some reason libupnp is only reading the first byte from the buffer we build.
I guess we are hitting some error condition in their code, so I will have to spend more time debugging that.
(you can see this yourself if you get a < as the the body of the AJAX calls in dev tools)

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/v00d00/gerbera","title":"v00d00/gerbera","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/v00d00/gerbera"}},"updates":{"snippets":[{"icon":"PERSON","message":"@v00d00 in #105: So I've had a quick chance to look at this, as far as I can see right now, Gerbera is doing everything correctly -  but for some reason libupnp is only reading the first byte from the buffer we build.\r\n\r\nI guess we are hitting some error condition in their code, so I will have to spend more time debugging that.\r\n\r\n(you can see this yourself if you get a `\u003c` as the the body of the AJAX calls in dev tools)"}],"action":{"name":"View Issue","url":"https://github.com/v00d00/gerbera/issues/105#issuecomment-321973776"}}}

**Comment by v00d00** [comment]
For some reason, running the below on ARM is giving me the output below.

Code snippet
```
    off_t temp = 1024;
    log_debug(">>> TEMP %d\n", temp);
    UpnpFileInfo_set_FileLength(info, temp); 
    log_debug(">>> SIZE %jd\n", (intmax_t)UpnpFileInfo_get_FileLength(info));
```
Output
```
2017-08-13 14:59:02   DEBUG: [src/web_request_handler.cc:101] get_info(): >>> TEMP 1024
2017-08-13 14:59:02   DEBUG: [src/web_request_handler.cc:103] get_info(): >>> SIZE 1
```

![image](https://media.giphy.com/media/glmRyiSI3v5E4/giphy-downsized-large.gif)

Ive looked at the code, and am lost, as it appears to just assign and read from a struct... and it appears to be fine on AMD64.

Ive raised an issue upstream to see if they have any idea. https://github.com/mrjimenez/pupnp/issues/51

**Comment by elmodaddyb** [comment]
Since you mention `struct`, I did some searching.  It seems like on `ARM` architecture, commonly systems have to account for memory address offsets vs `x86, x64` when referencing the internals of the `struct`, and even more-so when the internals are pointers.

I have very little knowledge on how ARM works, just hunting up info at this point.  No idea if it is truly relevant to this issue though.

https://stackoverflow.com/questions/22185848/how-to-re-use-c-structs-in-arm-assembly-in-a-maintainable-and-readable-way

**Comment by v00d00** [comment]
So this turns out to be caused by differing off_t sizes because we were not building with large file support.

I've added that in the latest commit (https://github.com/v00d00/gerbera/commit/d1b1ac6c2ffacf11fdd20d4bac38eda076b9bdca). The UI now loads as expected on my Pi.

**Comment by napopa** [comment]
Thanks @v00d00 ! it works here as well on raspbian

**Comment by LinuxUser2017** [comment]
Yay, Works for me too. (Raspbian)
Thanks team.

**Comment by Crazzilyme** [comment]
Doesn't login in Ubuntu-mate raspberry pi 3.
When logging in shows this error .
gerbera
2017-09-05 12:26:55    INFO: Gerbera UPnP Server version 1.0.0 - http://gerbera.io/
2017-09-05 12:26:55    INFO: =====================================================================                           ==========
2017-09-05 12:26:55    INFO: Gerbera is free software, covered by the GNU General Public License v                           ersion 2
2017-09-05 12:26:55    INFO: Copyright 2016-2017 Gerbera Contributors.
2017-09-05 12:26:55    INFO: Gerbera is based on MediaTomb: Copyright 2005-2010 Gena Batsyan, Serg                           ey Bostandzhyan, Leonhard Wimmer.
2017-09-05 12:26:55    INFO: Loading configuration from: /home/pi/.config/gerbera/config.xml
2017-09-05 12:26:55    INFO: Checking configuration...
2017-09-05 12:26:55    INFO: Setting filesystem import charset to UTF-8
2017-09-05 12:26:55    INFO: Setting metadata import charset to UTF-8
2017-09-05 12:26:55    INFO: Setting playlist charset to UTF-8
2017-09-05 12:26:55 WARNING: You enabled the YouTube feature, which allows you
                             to watch YouTube videos on your UPnP device!
                             Please check http://www.youtube.com/t/terms
                             By using this feature you may be violating YouTube
                             service terms and conditions!

2017-09-05 12:26:55    INFO: Configuration check succeeded.
2017-09-05 12:26:55 WARNING: IP is null
2017-09-05 12:26:55    INFO: Initialized port: 49152
2017-09-05 12:26:55    INFO: Server bound to: 192.168.1.2
2017-09-05 12:26:55    INFO: The Web UI can be reached by following this link: http://192.168.1.2:                           49152/
2017-09-05 12:27:02   ERROR: web_seek(): Exception during seek: MemIOHandler seek failed: unrecogn                           ized whence
Exception raised in [src/mem_io_handler.cc:151] seek(): MemIOHandler seek failed: unrecognized whe                           nce
2017-09-05 12:38:01   ERROR: web_seek(): Exception during seek: MemIOHandler seek failed: unrecogn                           ized whence
Exception raised in [src/mem_io_handler.cc:151] seek(): MemIOHandler seek failed: unrecognized whe                           nce
2017-09-05 12:40:01   ERROR: web_seek(): Exception during seek: MemIOHandler seek failed: unrecognized whence
Exception raised in [src/mem_io_handler.cc:151] seek(): MemIOHandler seek failed: unrecognized whence

**Comment by a-st** [comment]
Not sure whether to comment on this one or create a new issue, but I get the same issue again with current **master**. Running on Debian 11 armv7l.

![image](https://user-images.githubusercontent.com/63122/144604413-ecbe64a5-5855-4f5f-a571-f801d0824b66.png)
