### ISSUE TITLE
Cannot see the video thumbnails.

### ISSUE THREAD

**Issue by antenore** [v00d00/gerbera#123]
I cannot get the thumbnails with gerbera. I've tested with an LG TV and from VLC.

The exif and ffmpgegthumbnailer support are enabled.

Some interesting information I've found in the logfile:

```log
2017-07-26 21:45:24   DEBUG: [src/config_manager.cc:2182] getOption(): Config: option not found: /server/extended-runtime-options/ffmpegthumbnailer/cache-dir using default value:
2017-07-26 21:45:24   DEBUG: [src/config_manager.cc:2182] getOption(): Config: option not found: /server/extended-runtime-options/ffmpegthumbnailer/cache-dir/attribute::enabled using default value: yes
```

Defualt gerbera config:

```xml
<ffmpegthumbnailer enabled="yes">
        <thumbnail-size>128</thumbnail-size>
        <seek-percentage>5</seek-percentage>
        <filmstrip-overlay>yes</filmstrip-overlay>
       <image-quality>8</image-quality>
             <workaround-bugs>yes</workaround-bugs>
       <cache-dir enabled="yes"></cache-dir>
</ffmpegthumbnailer>
```
I've added the cache-dir option in my config but I've the same issue (but the error, so it should be ok)

Than I've several lines like:

```log
2017-07-26 21:45:25   DEBUG: [src/cds_resource_manager.cc:117] addResources(): Adding resource for video thumbnail
2017-07-26 21:45:25   DEBUG: [src/cds_resource_manager.cc:117] addResources(): Adding resource for video thumbnail
2017-07-26 21:45:25   DEBUG: [src/cds_resource_manager.cc:117] addResources(): Adding resource for video thumbnail
...
2017-07-26 21:45:25   DEBUG: [src/cds_resource_manager.cc:117] addResources(): Adding resource for video thumbnail
```
Before each video file

And finally the SQL queries, but I cannot say if the exif data has been added or not

For only one file I've got this message:

```
[src/metadata/ffmpeg_handler.cc:418] serveContent(): Generating thumbnail for file: /.........
....
[src/metadata/ffmpeg_handler.cc:392] serveContent(): Returning cached thumbnail for file:.........
```

I can provide the log file and the sql dump privately.

I won't be able to answer for some days.

**Comment by elmodaddyb** [comment]
I haven't used ffmpeg thumbnailer in gerbera, but had it working back in MT days. 

To clarify the expectation is to see the thumbnail of the movie in your upnp client?

**Comment by elmodaddyb** [comment]
I enabled the ffmpegthumbnailer using the xpath in the configuration file:
`/server/extended-runtime-options/ffmpegthumbnailer`
This did enable the feature.

When I hit Gerbera from my PS3,  I think thumbnails should be shown for an MP4 file.  It looks like the following is happening.
```
Request Handler --> FileRequestHandler.get_info(...)
URL --> "/content/media/object_id/37/res_id/0/ext/file.mp4"
```
Since `res_id` == 0 there the system does not enter into the FFMPEG handler code.  Looks like the `res_id` would have to parse as an acceptable # which would suite for `FfmpegHandler::serveContent`.  This would then result in the thumbnailer code execution.

My initial thought is somehow related to filetypes.  I am still working on understanding the server side behavior, so will post back any details I find.

**Comment by elmodaddyb** [comment]
OK bit of a learning experience on my part with DLNA.  It looks like the XML sent to the DLNA device is generated by this method:
```c
upp_xml::UpnpXML_DIDLRenderObject
```
This method adds the resources available in sequence for the specified **item** (movie, music, etc)
```
0 = file.mp4
1 = jpeg
n = etc, etc
```
If its a image, movie, container, etc the system generates different resources.  This makes sense.  So here is a generated entry for a movie file.
```xml
<item id="143" parentID="136" restricted="1">
    <dc:title>Movie.mp4</dc:title>
    <upnp:class>object.item.videoItem</upnp:class>
    <res protocolInfo="http-get:*:video/mp4:*" size="2067769601" bitrate="348797" duration="01:38:48.2"
         sampleFrequency="48000" nrAudioChannels="6" resolution="720x480">
        http://localhost:49153/content/media/object_id/143/res_id/0/ext/file.mp4
    </res>
    <res protocolInfo="http-get:*:image/jpeg:*" resolution="128x85">
        http://localhost:49153/content/media/object_id/143/res_id/1/rh/6/ext/file.jpg
    </res>
</item>
```
You can see the `2nd` resource `<res>` is the **thumbnail**.  This is a resource located on the server, which when requested, creates a new `FfmpegHandler` content handler, eventually calling `FfmpegHandler::serveContent`.  This actually works well.  When I request the thumbnail file path from a browser, I get the thumbnail!

> I think the server is working as expected

What I still need to figure out is 2 things.

1. Is the DLNA **client** actually calling for this resource
2. Is the **protocolInfo** correct for the DLNA client to *know* that it should make it a thumbnail.
Unfortunately, I don't know enough about DLNA clients just yet...I will keep you posted as I learn more.

Thanks,

E

**Comment by elmodaddyb** [comment]
I think I may have figured out the issue here.
> This feature may require additional code changes to work properly

For thumbnails to get **called for** by the DLNA client, the extended protocol info needs to be enabled in the configuration file `<protocolInfo extend="yes"/>`.

Once I enable this in CMakeLists.txt... the code does not compile due to some `}` curly braces out of place....that fixed...now receiving a `(interrupted by signal 11: SIGSEGV)` when sending back the rendered thumbnail due to content-size invalid.

It looks like we need to update the code to fix the following.

1. Enable `add_definitions(-DEXTEND_PROTOCOLINFO)` in `CMakeLists.txt` by some means
    `WITH_EXTENDED_PROTOCOL`??
2. Fix the curly braces around the `#ifdef EXTEND_PROTOCOLINFO` in `FileRequestHandler::get_info`
3. Fix the `Content-Length` header in [file_request_handler.cc](https://github.com/v00d00/gerbera/blob/master/src/file_request_handler.cc#L182)
4. Reconcile Extended protocols in [transcode_ext_handler](https://github.com/v00d00/gerbera/blob/master/src/transcoding/transcode_ext_handler.cc#L110)

Still working on validating this approach and will post a PR if all works out OK.

**Comment by v00d00** [comment]
One step toward this: https://github.com/v00d00/gerbera/commit/0d6ba4d74a384e7f667372c303ab4efcf48ff4c4

**Comment by elmodaddyb** [comment]
I will pull the latest master and see how it goes.

**Comment by elmodaddyb** [comment]
@v00d00 @antenore - I pulled the latest master at 7b102600f3ac312625b78fab519e2125cad8acce and with the `<protocolInfo extend="yes"/>` set in the `config.xml` was able to see the upnp client load **thumbnails** using my PS3.  I will try a few containers which have a lot of thumbnails to generate and report back the status.

Thanks,

E

**Comment by elmodaddyb** [comment]
:1st_place_medal: Ran aginst 40+ movies, loaded all thumbnails!

```
2017-08-06 14:28:02   DEBUG: [src/web_callbacks.cc:143] web_open(): web_open(): /content/media/object_id/750/res_id/1/rh/6/ext/file.jpg
2017-08-06 14:28:02   DEBUG: [src/web_callbacks.cc:57] create_request_handler(): Filename: /content/media/object_id/750/res_id/1/rh/6/ext/file.jpg, Path: (null)
2017-08-06 14:28:02   DEBUG: [src/file_request_handler.cc:331] open(): start
2017-08-06 14:28:02   DEBUG: [src/file_request_handler.cc:345] open(): full url (filename): /content/media/object_id/750/res_id/1/rh/6/ext/file.jpg, parameters: object_id/750/res_id/1/rh/6/ext/file.jpg
2017-08-06 14:28:02   DEBUG: [src/file_request_handler.cc:353] open(): Opening media file with object id 750
2017-08-06 14:28:02   DEBUG: [src/file_request_handler.cc:493] open(): fetching resource id 1
2017-08-06 14:28:02   DEBUG: [src/metadata/ffmpeg_handler.cc:418] serveContent(): Generating thumbnail for file: /movie.m4v
```

**Comment by antenore** [comment]
Yes! It works! I've tens of videos and I can see all the thumbnails. Thank you!
